# Generated by Django 5.2.5 on 2025-08-18 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=2025, unique=True)),
                ("address", models.CharField(max_length=1024)),
                ("capacity", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Station",
                "verbose_name_plural": "Stations",
            },
        ),
        migrations.CreateModel(
            name="Bike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=2055, null=True, verbose_name="Category"
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=1024, null=True)),
                ("brand", models.CharField(max_length=255, verbose_name="Bike Brand")),
                (
                    "electricity",
                    models.BooleanField(
                        default=False, help_text="Есть ли у него педали"
                    ),
                ),
                ("colour", models.CharField(max_length=1024)),
                ("available", models.BooleanField(default=True)),
                (
                    "comments",
                    models.TextField(
                        blank=True,
                        help_text="Тут мы храним всю итсорию о велосипеде и его обслуживании",
                        null=True,
                        verbose_name="Bike History",
                    ),
                ),
                (
                    "preview",
                    models.FileField(blank=True, null=True, upload_to="bike/preview"),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bikes",
                        to="bike.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bicycle",
                "verbose_name_plural": "Bicycles",
            },
        ),
    ]
