# Generated by Django 5.2.5 on 2025-08-27 16:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bike", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bike",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bike",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bike",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bikes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="bike",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="bike",
            name="brand",
            field=models.CharField(
                choices=[
                    ("trek", "Trek"),
                    ("giant", "Giant"),
                    ("specialized", "Specialized"),
                    ("cube", "Cube"),
                    ("author", "Author"),
                ],
                max_length=50,
                verbose_name="Bike Brand",
            ),
        ),
        migrations.AlterField(
            model_name="bike",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("road", "Шоссейный"),
                    ("mtb", "Горный"),
                    ("city", "Городской"),
                    ("electric", "Электровелосипед"),
                ],
                max_length=20,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="bike",
            name="colour",
            field=models.CharField(
                choices=[
                    ("red", "Красный"),
                    ("blue", "Синий"),
                    ("black", "Чёрный"),
                    ("white", "Белый"),
                    ("green", "Зелёный"),
                ],
                max_length=20,
                verbose_name="Colour",
            ),
        ),
        migrations.AlterField(
            model_name="bike",
            name="comments",
            field=models.TextField(
                blank=True,
                help_text="Тут мы храним всю историю о велосипеде и его обслуживании",
                null=True,
                verbose_name="Bike History",
            ),
        ),
    ]
